# Generated by Django 3.1.7 on 2021-03-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='address',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=80),
        ),
    ]
