# Generated by Django 3.1.7 on 2021-03-23 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210318_1118'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('demand', 'name')},
        ),
    ]
